server:
  port: 9999
  
spring:
  application:
    name: zuul-proxy
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  prefix: /api
  routes:
    test-redirect:
      path: /redirect/**
      location: http://www.google.co.in
    test-by-service:
      path: /service/**
      location: emp-service
    test-by-hr-service:
       path: /client/**
       location: hr-service